---
repository:
  description: VSCode Devcontainer for Elixer
  homepage: https://github.com/hspaans/vscode-devcontainer-elixer
  topics: vscode, devcontainer, elixer
  delete_branch_on_merge: true
  has_wiki: false
